#This config file is specificated for theme demo page : https://riino.site/jekyll-theme-panda/
#Please do not use this config directly if you desire to use this repo as your blog.
title: jekyll-theme-panda
author: riino
email: riino@gmail.com
SEOTitle: jekyll-theme-panda demo
baseurl: "/jekyll-theme-panda" # the subpath of your site, e.g. /blog
url: "https://riino.site" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sorphwer
github_username: sorphwer
github_url: https://github.com/sorphwer
repo_url: https://github.com/sorphwer/jekyll-theme-panda
theme_version: 0.2.5
permalink: /:year-:month-:day-:title:output_ext
# Build settings
# markdown: kramdown
# kramdown:
#   input: GFM
#   syntax_highlighter: rouge

markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag
paginate: 10

toc:
  min_level: 1 # default: 1
  max_level: 4 # default: 6
sass:
    sass_dir: _sass
    style: compressed

navigation:
- text: Blogs
  url: index.html
  layout: home
- text: Archive
  url: Archive
  layout: forarchive
- text: Albums
  url: Albums
  layout: albumlist
- text: Presets
  url: Presets
  layout: presetlist
- text: About
  url: About1
  layout: about




dropdown_header: Theme #will only exist if dropdown array below has item(s)
dropdown:
- text: BLOG
  url: https://riino.site


footer_text:
- jekyll-theme-panda demo by Riino
- All Rights Reserved.

footer_html: <a href="{{ site.baseurl }}/feed.xml">RSS Subscribe |</a><span></span><a href="{{ site.baseurl }}/policy/">Policy</a>

banner_img: /assets/img/banner.gif
hoster_logo: /assets/img/logo_Nest.png
hoster_logo_link: https://github.com/sorphwer
hoster_logo_alt: Github
hoster_text:
- Nest of Etamine - 10th Anniversary
- 2012-2022


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
# this goes inside _config.yml. Change as required